project:
  type: website
  output-dir: docs
  
engine: knitr
execute:
  freeze: auto
  
layout: article
editor: visual

format:
  html:
    comments:
      hypothesis:
        theme: clean
        openSidebar: false
    theme:
       - darkly
       - 'scss/main.scss'

#manuscript:
#  article: index.qmd
#  code-links: 
#    - text: Data Import
#      icon: file-code
#      href: https://github.com/ericMossotti/problematicHabits
#  notebooks: 
#    - notebook: 'notebooks/data-modeling.qmd'
#      title: "Data Model Schematic"







