project:
  type: website
  output-dir: docs
  render: 
    - index.qmd
    - "!practice/"
  
engine: knitr
execute:
  freeze: auto
  
layout: article
editor: visual

format:
  html:
    comments:
      hypothesis:
        theme: clean
        openSidebar: false
    theme:
       - darkly
       - 'scss/main.scss'






